"""Render the regime, explanation, error and friction analysis into docs/ANALYSIS.md.

Separate from make_results.py because this needs the panel and the price cache, while
that one runs from the recorded metrics alone.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

from market_forecast.backtest.simulate import break_even_cost_bps, buy_and_hold, cost_sweep
from market_forecast.config import get_config, project_root
from market_forecast.data.loader import default_loader
from market_forecast.dataset import load_panel
from market_forecast.evaluation.error_analysis import (
    confidence_deciles,
    error_breakdown,
    performance_around_reversals,
    performance_by_bucket,
    performance_by_group,
)
from market_forecast.experiments.tracker import ExperimentTracker
from market_forecast.explain.shap_explainer import ShapExplainer
from market_forecast.features.indicators import log_return
from market_forecast.logging import configure, get_logger
from market_forecast.models.registry import build_model, default_specs
from market_forecast.regime.describe import describe_states, label_states
from market_forecast.regime.features import breadth_from_panel, build_regime_features
from market_forecast.regime.pipeline import assign_by_fold
from market_forecast.regime.select import compare
from market_forecast.validation.splits import WalkForwardSplitter

logger = get_logger(__name__)


def md(frame: pd.DataFrame, index: bool = True) -> str:
    """Render a table, keeping a named index as its first column and dropping an unnamed one."""
    prepared = frame.reset_index() if index and frame.index.name else frame
    return prepared.to_markdown(index=False)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", default="excess_direction")
    parser.add_argument("--horizon", type=int, default=1)
    parser.add_argument("--model", default="lightgbm")
    parser.add_argument("--states", type=int, default=3)
    parser.add_argument("--out", default=None)
    parser.add_argument("--log-level", default="WARNING")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    configure(args.log_level)
    config = get_config()

    panel = load_panel(project_root() / "artifacts" / f"panel_{config.features.version}.parquet")
    dev = panel.frame[panel.frame["group"] == "dev"]
    loader = default_loader(config.data)
    benchmark = loader.load(config.universe.benchmark).frame
    volatility_index = loader.load(config.universe.volatility_index, raise_on_error=False).frame

    tracker = ExperimentTracker()
    index = tracker.index()
    run = index[
        (index["experiment"] == "main")
        & (index["target"] == args.target)
        & (index["horizon"] == args.horizon)
    ].iloc[-1]
    predictions = tracker.load_predictions(run["run_id"])
    chosen = predictions[predictions["model"] == args.model]

    label = f"{args.target}_{args.horizon}d"
    rows = dev[dev[label].notna()]
    dates = pd.Series(rows.index.get_level_values("date"), index=rows.index)
    sessions = pd.DatetimeIndex(dates.unique()).sort_values()
    folds = WalkForwardSplitter(config.walkforward, args.horizon).split(sessions)

    features = build_regime_features(benchmark, volatility_index, breadth_from_panel(dev))
    market_returns = log_return(benchmark["close"], 1)

    lines: list[str] = [
        "# Analysis",
        "",
        "Generated by `scripts/make_analysis.py`. Do not edit by hand.",
        "",
        f"Subject: `{args.target}` at {args.horizon} session"
        f"{'s' if args.horizon > 1 else ''}, model `{args.model}`, run `{run['run_id']}`.",
        "",
        "## Regime detection",
        "",
        "### Choosing the method",
        "",
        "Selection is not by likelihood alone. A mixture fits better in sample while",
        "producing states that change every few days, which is useless as market context.",
        "k-means defines no likelihood, so its BIC column is empty rather than misleading.",
        "",
    ]
    train = features.loc[: str(folds[0].fit_dates[1].date())]
    lines += [md(compare(train).round(3), index=False), ""]

    assigned = assign_by_fold(features, folds, "hmm", args.states, seed=config.walkforward.seed)
    summary = describe_states(features.loc[assigned.labels.index], assigned.labels, market_returns)
    names = label_states(summary)
    summary = summary.assign(label=[names[int(s)] for s in summary.index])

    lines += [
        "### The fitted states",
        "",
        "The estimator numbers states arbitrarily. Labels below are generated from each",
        "state's own statistics after fitting, so no cluster was called bullish or bearish",
        "in advance. Regimes are refitted inside every fold and applied by forward",
        "filtering, so the regime attached to a session was knowable at that session.",
        "",
        md(summary.round(4)),
        "",
        "### Forecast performance by regime",
        "",
        "Measured as lift over the majority baseline on the same rows, which removes the",
        "drift in fold base rates that would otherwise show up as skill.",
        "",
    ]

    volatility = features["mkt_vol_20"].reindex(assigned.labels.index)
    order = {
        int(s): r
        for r, s in enumerate(volatility.groupby(assigned.labels).mean().sort_values().index)
    }
    regime = assigned.labels.map(order).rename("regime")
    joined = predictions.reset_index().merge(
        regime.rename_axis("date").reset_index(), on="date", how="inner"
    )

    from sklearn.metrics import roc_auc_score

    baseline = joined[joined["model"] == "majority"]
    regime_rows = []
    for model in [m.name for m in default_specs() if not m.is_baseline] + ["persistence"]:
        block = joined[joined["model"] == model]
        row: dict[str, object] = {"model": model}
        for state in sorted(regime.unique()):
            a = block[block["regime"] == state]
            b = baseline[baseline["regime"] == state]
            row[f"regime{state}_auc"] = round(float(roc_auc_score(a["y_true"], a["prob"])), 4)
            row[f"regime{state}_lift"] = round(
                float(
                    roc_auc_score(a["y_true"], a["prob"]) - roc_auc_score(b["y_true"], b["prob"])
                ),
                4,
            )
        regime_rows.append(row)
    lines += [md(pd.DataFrame(regime_rows).set_index("model")), ""]

    character = []
    for state in sorted(regime.unique()):
        selected = regime[regime == state].index
        character.append(
            {
                "regime": state,
                "sessions": len(selected),
                "mkt_vol_20": round(float(features.loc[selected, "mkt_vol_20"].mean()), 4),
                "mkt_ret_20": round(float(features.loc[selected, "mkt_ret_20"].mean()), 4),
                "breadth": round(float(features.loc[selected, "breadth_above_sma50"].mean()), 4),
                "realised_ann_return": round(
                    float(market_returns.reindex(selected).mean() * 252), 4
                ),
            }
        )
    lines += [
        "Regime character over the test sessions:",
        "",
        md(pd.DataFrame(character), index=False),
        "",
    ]

    last = folds[-1]
    fit = rows[last.mask(dates, "fit").to_numpy()]
    test = rows[last.mask(dates, "test").to_numpy()]
    spec = next(s for s in default_specs() if s.name == args.model)
    model = build_model(spec, seed=config.walkforward.seed).fit(
        fit[panel.feature_names], fit[label]
    )
    explainer = ShapExplainer(model)
    importance = explainer.explain_global(test[panel.feature_names])

    lines += [
        "## Explainability",
        "",
        "Contributions are in log-odds, the space the trees add in, so the base value plus",
        "the contributions reconstructs the prediction exactly. An attribution describes",
        "what this model did with correlated inputs. It is not evidence that a feature",
        "causes future returns.",
        "",
        f"Global importance on the final fold's test window ({len(test):,} rows):",
        "",
        md(importance.head(15).round(5)),
        "",
    ]

    lines += [
        "## Error analysis",
        "",
        "### Outcome breakdown",
        "",
        md(error_breakdown(chosen).round(4)),
        "",
    ]
    deciles = confidence_deciles(chosen)
    lines += [
        "### Accuracy by confidence decile",
        "",
        "A model that knows what it does not know shows accuracy rising with confidence.",
        "",
        md(deciles.round(4)),
        "",
    ]
    for column, title in (
        ("vol_20", "the stock's own volatility"),
        ("bench_vol_20", "market volatility"),
        ("beta_60", "beta"),
    ):
        conditioning = dev[column].reindex(chosen.index)
        table = performance_by_bucket(
            chosen, conditioning, 5, ["Q1 low", "Q2", "Q3", "Q4", "Q5 high"]
        )
        lines += [f"### By {title}", "", md(table.round(4)), ""]

    per_ticker = performance_by_group(chosen)
    lines += [
        "### By ticker",
        "",
        f"AUC ranges from {per_ticker['roc_auc'].min():.4f} to {per_ticker['roc_auc'].max():.4f} "
        "across the development universe, so any aggregate figure hides considerable spread.",
        "",
        md(per_ticker.round(4)),
        "",
    ]

    trend = dev["px_to_sma_50"].groupby(level="date").mean()
    reversals = performance_around_reversals(chosen, trend)
    lines += [
        "### Around trend reversals",
        "",
        f"- near a reversal: {reversals.around_reversals:.4f} ({reversals.n_reversal_rows:,} rows)",
        f"- elsewhere: {reversals.elsewhere:.4f} ({reversals.n_other_rows:,} rows)",
        f"- difference: {reversals.gap:+.4f}",
        "",
        "## Friction",
        "",
        "This is a check on whether an edge of this size survives costs, not a trading",
        "strategy. Fills are assumed at the close, market impact and capacity are ignored,",
        "borrow on the short leg is free, and the universe contains only surviving firms.",
        "Every one of those assumptions flatters the result.",
        "",
    ]

    excess = dev[f"fwd_excess_ret_{args.horizon}d"]
    raw = dev[f"fwd_ret_{args.horizon}d"]
    lines += [
        "### Market neutral: long the name, short the benchmark",
        "",
        md(cost_sweep(chosen, excess).round(4)),
        "",
        f"Break-even round-trip cost: **{break_even_cost_bps(chosen, excess):.2f} bps**.",
        "",
        "### Long only, against doing nothing",
        "",
        md(cost_sweep(chosen, raw).round(4)),
        "",
    ]
    hold = buy_and_hold(raw.reindex(chosen.index).dropna())
    lines += [
        f"Break-even round-trip cost: **{break_even_cost_bps(chosen, raw):.2f} bps**.",
        "",
        f"Equal-weighted buy and hold over the same sessions returns "
        f"{hold.annualised_return:+.2%} a year at {hold.annualised_volatility:.2%} volatility, "
        f"Sharpe {hold.sharpe:.2f}, with no turnover at all.",
        "",
    ]

    out = Path(args.out) if args.out else project_root() / "docs" / "ANALYSIS.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
